/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 00400e3000e99c8b5cf39bdd19f68080)
interface __BaseEnv_Env {
	SONG_RATE_LIMIT: KVNamespace;
	SONGS: R2Bucket;
	AI_ACCOUNT_ID: "8d2b0d67bfcd46cf2e40eed93b716660";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_ACCOUNT_ID">> {}
}
